### PR TITLE
Kulak_Prohor_Lab1

### PR DESCRIPTION
**Pull request by lagatun54**
Option 21
Topic: "The system of disjoint sets"

1. Made functions for sets
- Creation of a set.
- The union of two sets.
- Definition of the set to which
- The closest element.

2. Made a library for the functions themselves
3. Made Unit-test based on a single-head framework with self-registration of tests (Doctest)

Need to download СMake and Doctest

Link Doctest: [push](https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h)

### CODE REVIEW

**Comment by Zioba** [comment]
MR description is good,

but learn to write in english

**Comment by Zioba** [comment]
remove cmake-build-debug from PR
or add it to .gitignore

**Review by Zioba — CHANGES_REQUESTED** [review]
remove cmake-build-debug from PR
or add it to .gitignore

**Comment by lagatun54** [comment]
Option 21
Topic: "The system of disjoint sets"

Made functions for sets
Creation of a set.
The union of two sets.
Definition of the set to which
The closest element.
Made a library for the functions themselves

Made Unit-test based on a single-head framework with self-registration of tests (Doctest)

**Review by lagatun54 — COMMENTED** [review]
Option 21
Topic: "The system of disjoint sets"

1. Made functions for sets
- Creation of a set.
- The union of two sets.
- Definition of the set to which
- The closest element.

2. Made a library for the functions themselves
3. Made Unit-test based on a single-head framework with self-registration of tests (Doctest)

Need to download СMake and Doctest

Link Doctest: [push](https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h)

**Review by Zioba — APPROVED** [review]

**Pull request merged**
